### ISSUE TITLE
Issues running ggplot code

### ISSUE THREAD

**Issue by novotny1akub** [coatless-r-n-d/webR-quarto-demos#1]
Combining Quarto and webR is really cool. However, I run into one problem when running your example. It seems like the ggplot code does not seem to be working. When I try to run it, it takes a lot of time, and there is no output. Do you know what might by the problem?

**Comment by coatless** [comment]
Thanks for the question. In short, the `ggplot2` cell requires `ggplot2` to be installed which takes time due to the dependency count. That is, the slowdown happens due to: 

```r
webr::install("ggplot2")
```

Unfortunately, there isn't an easy way to speed up the installation at the moment.

Though, once `ggplot2` is installed, then it can be used in future cells without the time penalty.

**Comment by novotny1akub** [comment]
I see. Thank you for the answer. How long does it take for you to install `ggplot2`? I tried to be patient, but nothing seemed to be happening.

**Comment by coatless** [comment]
The installation time of `ggplot2` depends on your computer hardware. It usually should take at least **2 minutes** without the headers being set. c.f. gif (~1 min 37s):

![ggplot2-install](https://user-images.githubusercontent.com/833642/226461744-d7ec6964-2aaf-4fc3-95fe-74462169f9cc.gif)

Note: If you enable the COOP and COEP as described here, the load time can decrease drastically to around 10s+ from 1min +

https://github.com/coatless/quarto-webr#speed-up-webr
